export const SET_PAGE_TYPE = 'SET_PAGE_TYPE'
export const SET_YES_NO = 'SET_YES_NO'          
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'     
export const SET_QUESTION_DATA = 'SET_QUESTION_DATA'  
export const SET_ANSWER = 'SET_ANSWER'    
export const SET_BONUS_DATA = 'SET_BONUS_DATA'  
export const SET_BONUS_SELECTED = 'SET_BONUS_SELECTED'  
export const SET_ITEMS_DATA = 'SET_ITEMS_DATA'   
export const SET_ITEM = 'SET_ITEM'   
export const SET_BONUS_ANSWER = 'SET_BONUS_ANSWER'   
export const SET_IS_BONUS = 'SET_IS_BONUS'
export const SET_FADE = 'SET_FADE'  
export const TRIGGER_RESIZE = 'TRIGGER_RESIZE'
export const SET_NUM_PAGES = 'SET_NUM_PAGES'
export const SET_NICKNAME = 'SET_NICKNAME'
export const SET_WORKAREA = 'SET_WORKAREA'

// auth actions

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
